name: Android Release CI

on:
  pull_request:
    branches: [master]

jobs:
  #  KtLint Check
  ktlint_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run ktlint check
        run: ./gradlew ktlintCheck --continue
  #  Lint Check
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run lint check
        run: ./gradlew lintRelease
  #  Detekt Check
  detekt_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run detekt check
        run: ./gradlew detektRelease
  #  Unit Test Check
  test:
    needs: [lint_check, ktlint_check, detekt_check]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run test
        run: ./gradlew testReleaseUnitTest
  #  Instrumentation Test Check
  #  android_test:
  #    needs: [lint_check, ktlint_check, detekt_check, test]
  #    runs-on: ubuntu-20.04
  #    steps:
  #      - uses: actions/checkout@v2
  #      - uses: actions/setup-java@v1
  #        with:
  #          java-version: 11
  #      - name: Make gradlew executable
  #        run: chmod +x ./gradlew
  #      - name: Build APK for UI test after Unit tests
  #        run: |
  #          ./gradlew test
  #          ./gradlew assembleDebug
  #          ./gradlew assembleDebugAndroidTest
  #      - name: Firebase auth with gcloud
  #        uses: google-github-actions/setup-gcloud@master
  #        with:
  #          version: '290.0.1'
  #          service_account_key: ${{ secrets.FIREBASE_KEY }}
  #          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
  #
  #      - name: Run Instrumentation Tests in Firebase Test Lab
  #        run: |
  #          gcloud firebase test android models list
  #          gcloud firebase test android run --type instrumentation --use-orchestrator --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device model=Pixel2,version=30,locale=en,orientation=portrait
  #  Build artifact
  build:
    needs:
      - lint_check
      - ktlint_check
      - detekt_check
#      - android_test
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Checkout Android Keystore
        uses: actions/checkout@v2
        with:
          repository: andriy1507/release-credentials
          token: ${{ secrets.KEYSTORE_TOKEN }}
          path: keystore
      - name: Assemble release apk
        run: ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/release/**.apk